version: "3.7"

services:
  quests_db:
    image: postgres
    container_name: quests-postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quests
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d quests -U user" ]
      interval: 30s
      timeout: 30s
      retries: 3